# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: ant CI test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:           
  containertest:
    runs-on: ubuntu-latest
    container:
      image: mm0820/ant_test:0.1
    steps: 
    - name: test
      run: |
        echo $JAVA_HOME
    - uses: actions/checkout@v3
    - name: test2
      run: |
        ant -noinput -buildfile build/build.xml
        ls -al

        

