# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: in_container_test

on:
  workflow_dispatch: 
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  in_container_build:
    runs-on: ubuntu-latest
    container:
      image: debian:11
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build with Ant
        run: |
          ant/bin/ant -noinput -buildfile build/build.xml
          whoami
      - uses: actions/upload-artifact@v3
        with:
          name: testwar
          path: build/build/helloworld-0.1-dev.war  
  scp:
    name: scp
    runs-on: ubuntu-latest
    needs: in_container_build
    container:
      image: debian:11
      options: --user root
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: testwar
      - name: tar create
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf ant.tar ../build/
          ls -al
          whoami
      - uses: appleboy/scp-action@master
        with:
          host: 43.201.105.29
          username: Administrator
          password: ${{ secrets.PASSWORD3 }}
          port: ${{ secrets.PORT }}
          source: ./*.tar
          target: '\USERS\Administrator'
  ssh: 
    name: ssh
    runs-on: ubuntu-latest
    needs: scp
    container:
      image: debian:11
    steps:
    - uses: actions/checkout@v3
    - name: ssh test
      uses: appleboy/ssh-action@master
      with:
        host: 43.201.105.29
        username: Administrator
        password: ${{ secrets.PASSWORD3 }}
        port: ${{ secrets.PORT }}
        script: dir
          
        


