name: branch_test

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs: 
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        ref: test
    - name: tar
      run: |
        tar -cvf test3.tar test3/*.html
        #sh win.sh
        tar -tvf test3.tar
