name: maven test

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: adopt 
    - name: Build with Maven
      run: |
        cd test2
        mvn package
    - uses: actions/upload-artifact@v3
      with:
        name: test2
        path: test2/target/test2.war
  scp:
    name: scp
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: test2
    - name: Run a multi-line script
      run: |
        ls -al
        mkdir ../build
        cp *.war ../build
        tar -cvf deploy1.tar ../build/
        ls -al
    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST2 }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source:  deploy1.tar
        target: /home/ubuntu/
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: scp
    steps:
    - uses: actions/checkout@v3
    - name: ssh 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST2 }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          tar -xvf deploy1.tar -C .
          cd build 
          mv test2.war /usr/local/bin/apache-tomcat-9.0.69/webapps/
          ls -al /usr/local/bin/apache-tomcat-9.0.69/webapps/
          bash /usr/local/bin/apache-tomcat-9.0.69/bin/startup.sh
