name: windowtest2

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: test
    steps:
    - name: Run sshpass command
      with:
        run: | 
          bash sshpass "${{ secrets.SERVER_PASS }}" ssh Administrator@13.209.89.118 -o StrictHostKeyChecking=no
          
