name: windowtest3

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs: 
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - name: tar
      run: |
        tar -cvf test3.tar test3/*.html
        sh win.sh
        curl 3.39.10.170/test1.html
        curl 3.39.10.170/test.html
