
name: windowtest

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
jobs: 
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
    - name: tar
      run: |
        #mkdir ../build
        #cp *.html ../build
        #tar -cvf deploy3.tar ../build/
        ls -al    
    - name: ssh key with passphrase
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST2 }}
        username: ${{ secrets.USERNAME2 }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "test.html"
        target: "c:/inetpub/wwwroot"
           
